// Mocks generated by Mockito 5.4.6 from annotations
// in prueba_experis/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prueba_experis/core/services/remote_config_service.dart' as _i2;
import 'package:prueba_experis/features/data/models/product_model.dart' as _i5;
import 'package:prueba_experis/features/presentation/viewmodels/product_view_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RemoteConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigService extends _i1.Mock
    implements _i2.RemoteConfigService {
  @override
  bool get showOffersSection =>
      (super.noSuchMethod(
            Invocation.getter(#showOffersSection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ProductViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductViewModel extends _i1.Mock implements _i4.ProductViewModel {
  @override
  _i4.ViewState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i4.ViewState.loading,
            returnValueForMissingStub: _i4.ViewState.loading,
          )
          as _i4.ViewState);

  @override
  List<_i5.ProductModel> get products =>
      (super.noSuchMethod(
            Invocation.getter(#products),
            returnValue: <_i5.ProductModel>[],
            returnValueForMissingStub: <_i5.ProductModel>[],
          )
          as List<_i5.ProductModel>);

  @override
  set state(_i4.ViewState? _state) => super.noSuchMethod(
    Invocation.setter(#state, _state),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> fetchProducts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addProduct(_i5.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateProduct(_i5.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> searchProducts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [query]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleFavoriteStatus(_i5.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavoriteStatus, [product]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void showLoading() => super.noSuchMethod(
    Invocation.method(#showLoading, []),
    returnValueForMissingStub: null,
  );

  @override
  void showContent() => super.noSuchMethod(
    Invocation.method(#showContent, []),
    returnValueForMissingStub: null,
  );

  @override
  void showError() => super.noSuchMethod(
    Invocation.method(#showError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
